# Generated by Django 4.1.7 on 2023-02-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=3)),
                ('currentPrice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasedPrice', models.IntegerField(default=0)),
                ('currentPrice', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
                ('stockId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotrade.stock')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotrade.user')),
            ],
        ),
    ]
