# Generated by Django 4.1.7 on 2023-03-01 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotrade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedstock',
            name='currentPrice',
        ),
    ]
