# Generated by Django 4.1.7 on 2023-05-16 06:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import dotrade.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dotrade', '0005_comment_created_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.RegexValidator('^[a-zA-Z0-9\\s.]+$', 'Only alphanumeric characters, spaces and full stops are allowed.')]),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'Only alphabets allowed')])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'Only alphabets allowed')])),
                ('credit_card', dotrade.models.EncryptedField()),
                ('date_of_birth', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
