# Generated by Django 4.1.7 on 2023-05-17 07:08

from django.db import migrations, models
import dotrade.models


class Migration(migrations.Migration):

    dependencies = [
        ('dotrade', '0006_alter_comment_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credit_card',
            field=dotrade.models.EncryptedField(editable=True),
        ),
    ]
