# Generated by Django 4.1.7 on 2023-05-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotrade', '0007_profile_consent_alter_profile_credit_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='consent',
            new_name='save_payment_information',
        ),
    ]
