# Generated by Django 4.1.7 on 2023-05-17 10:37

from django.db import migrations
import dotrade.models


class Migration(migrations.Migration):

    dependencies = [
        ('dotrade', '0008_rename_consent_profile_save_payment_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credit_card',
            field=dotrade.models.EncryptedField(editable=True, null=True),
        ),
    ]
